version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: notes_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - notes-network

  app:
    build: .
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_DATABASE: notes_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    networks:
      - notes-network

networks:
  notes-network:

volumes:
  db_data:

